[versions]
coreKtxVersion = "1.12.0"
composeVersion = "1.5.4"
composeMaterial3Version = "1.1.2"
activityComposeVersion = "1.8.2"
multidexVersion = "2.0.1"
okhttpVersion = "4.12.0"
gsonVersion = "2.10.1"
glideVersion = "5.0.0-rc01"
retrofitVersion = "2.9.0"
lifecycleVersion = "2.6.2"
koinCoreVersion = "3.5.3"
koinVersion = "3.5.3"
pluginSerializationVersion = "1.7.20"
coroutinesVersion = "1.7.3"
glideComposeVersion = "1.0.0-beta01"
dataStoreVersion = "1.0.0"
navigationVersion = "2.7.6"
hazeVersion = "0.4.3"
readmoreVersion = "1.4.4"
youtubeplayerVersion = "12.1.0"
roomVersion = "2.6.1"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleVersion" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycleVersion" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidexVersion" }

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeVersion" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeVersion" }
compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeVersion" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3Version" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationVersion" }

glideCompose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glideComposeVersion" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStoreVersion" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "dataStoreVersion" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glideVersion" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glideVersion" }
glide-okhttp3-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glideVersion" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesVersion" }

okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttpVersion" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpVersion" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koinCoreVersion" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinVersion" }
koin-compose-navigation = { group = "io.insert-koin", name = "koin-androidx-compose-navigation", version.ref = "koinVersion" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinVersion" }

haze-jetpack-compose = { group = "dev.chrisbanes.haze", name = "haze-jetpack-compose", version.ref = "hazeVersion" }
readmore-material = { group = "com.webtoonscorp.android", name = "readmore-material", version.ref = "readmoreVersion" }
youtubeplayer = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "youtubeplayerVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "pluginSerializationVersion" }