name: Analyze, Test and Build for Android

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  lint:
    name: Analyze the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - run: ./gradlew lintRelease

  build:
    name: Build apk
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Create version number
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: version-string
        run: echo "VERSION_STR=$(echo ${{ github.ref }} | cut -d '/' -f 3 | cut -c2-)" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionName: ${{ steps.version-string.outputs.VERSION_STR }}

      - name: Update KeyStore password in key properties
        run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' key.properties

      - name: Update KeyStore key password in key properties
        run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' key.properties

      - name: Update key alias in key properties
        run: sed -i 's/#{KEY_ALIAS}#/${{ secrets.KEY_ALIAS }}/g' key.properties

      - name: Build Android APK
        run: ./gradlew assembleRelease

      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/app-release.apk"
          token: ${{ secrets.TOKEN_GITHUB }}
          tag: ${{ github.ref }}
          commit: ${{ steps.version-string.outputs.VERSION_STR }}
          prerelease: false

      - name: Upload app apk
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: app/build/outputs/apk/release/app-release.apk

  firebase_distribution:
    name: Release app to firebase distribution
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get app apk from artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-release

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app-release.apk
          releaseNotes: ${{ github.sha }}
