name: Analyze, Test and Build for Android

on:
  push:
    branches:
      - master

jobs:

  lint:
    name: Analyze the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - run: ./gradlew lintRelease

  build:
    name: Build apk
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Extract version name
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Update KeyStore password in key properties
        run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' key.properties

      - name: Update KeyStore key password in key properties
        run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' key.properties

      - name: Update key alias in key properties
        run: sed -i 's/#{KEY_ALIAS}#/${{ secrets.KEY_ALIAS }}/g' key.properties

      - name: Build Android APK
        run: ./gradlew assembleRelease

      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "app/build/outputs/apk/release/app-release.apk"
          token: ${{ secrets.TOKEN_GITHUB }}
          tag: ${{ env.VERSION }}
          commit: ${{ github.sha }}
          prerelease: false

      - name: Upload app apk
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: app/build/outputs/apk/release/app-release.apk

  firebase_distribution:
    name: Release app to firebase distribution
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get app apk from artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-release

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.9.0
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app-release.apk
